# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en"
tone_instructions: ""
early_access: true
enable_free_tier: true
inheritance: true
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_instructions: |
    Extract the Jira issue key from the PR title (format: MPT-XXXX).
    Start the summary with: "Closes MPT-XXXX" where MPT-XXXX is replaced with the actual issue key found in the title.
    Add a link: [MPT-XXXX](https://softwareone.atlassian.net/browse/MPT-XXXX)

    Then generate concise release notes as a bullet-point list.
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: false
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: false
  related_prs: true
  suggested_labels: false
  labeling_instructions: []
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  in_progress_fortune: false
  poem: false
  enable_prompt_for_ai_agents: true
  path_filters:
      - "!.gitignore"
  path_instructions:
      - path: "**/*.py"
        instructions: |
          Do not suggest formatting changes or mention code formatting using Black. Instead use Ruff or Flake8
      - path: "**/*"
        instructions: |
          When reviewing subsequent commits, always check if previous review comments have been addressed and acknowledge resolved issues.
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    ignore_usernames: []
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  pre_merge_checks:
    docstrings:
      mode: off
    title:
      mode: off
    description:
      mode: off
    issue_assessment:
      mode: warning
    custom_checks:
      - name: "Jira Issue Key in Title"
        mode: "error"
        instructions: |
          Check if the PR title contains exactly one Jira issue key in the format MPT-XXXX.

          If found:
          - Post: ✅ Found Jira issue key in the title: [MPT-XXXX](https://softwareone.atlassian.net/browse/MPT-XXXX)
          - Replace MPT-XXXX with the actual issue key found
          - Mark the check as PASSED

          If not found:
          - Post: ⚠️ PR title must include exactly one Jira issue key in the format MPT-XXXX.
          - Mark the check as FAILED
      - name: "Test Coverage Required"
        mode: "warning"
        instructions: |
          Check if the PR modifies any code files but does not include changes in the tests/ folder.

          If code files are modified but no test files are changed:
          - Count the number of code files modified
          - Post: This PR modifies code (X file(s)) but does not include any changes in the tests/ folder. Please consider adding or updating tests to cover your changes.
          - Replace X with the actual number of files
          - Mark the check as FAILED

          If test files are included or no code files are modified:
          - Mark the check as PASSED
      - name: "Single Commit Required"
        mode: "warning"
        instructions: |
          Check if the PR contains more than one commit.

          If the PR has more than one commit:
          - Count the number of commits
          - Post: ⚠️ This PR contains X commits. Please squash them into a single commit to keep the git history clean and easy to follow. Multiple commits are acceptable only in the following cases: One commit is a technical refactoring, and another introduces business logic changes. You are doing a complex multi-step refactoring (although in this case we still recommend splitting it into separate PRs).
          - Replace X with the actual number of commits
          - Mark the check as FAILED

          If the PR has exactly one commit:
          - Mark the check as PASSED
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: false
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
      level: default
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    golangci-lint:
      enabled: false
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: false
    detekt:
      enabled: false
    eslint:
      enabled: false
    flake8:
      enabled: true
    fortitudeLint:
      enabled: false
    rubocop:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    actionlint:
      enabled: true
    pmd:
      enabled: true
    clang:
      enabled: false
    cppcheck:
      enabled: false
    semgrep:
      enabled: true
    circleci:
      enabled: false
    clippy:
      enabled: false
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    pylint:
      enabled: true
    oxc:
      enabled: false
    shopifyThemeCheck:
      enabled: false
    luacheck:
      enabled: false
    brakeman:
      enabled: false
    dotenvLint:
      enabled: false
    htmlhint:
      enabled: false
    checkmake:
      enabled: true
    osvScanner:
      enabled: true
chat:
  art: false
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: disabled
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []  # Uses defaults including .github/copilot-instructions.md
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: enabled
    project_keys:
      - MPT
  pull_requests:
    scope: auto
  mcp:
    usage: auto
    disabled_servers: []
