# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
remote_config:
  url: "https://raw.githubusercontent.com/softwareone-platform/mpt-tool/229eb147b0d691a3d4e0d08985cf9d6cf05c19b5/.coderabbit.yaml"
